### ISSUE TITLE
Publish ESLint 2.x support to the NPM registry

### ISSUE THREAD

**Issue by justinhelmer** [sindresorhus/eslint-config-xo#15]
Added by https://github.com/sindresorhus/eslint-config-xo/commit/56a33c64af556f7a24349c8e57ba10cb1cc85664

Will close
    - **[** #13 (bump minor version) **]**
    - **[** #14 (bump patch version) **]**

Blocker for https://github.com/google/eslint-config-google/issues/6 (`ESLint 2.x` support for [eslint-config-google](https://github.com/google/eslint-config-google/))

**Comment by justinhelmer** [comment]
I'm assuming you have some other things you want to do but I've just set this up to subscribe to changes so I can fire off [#6](https://github.com/google/eslint-config-google/issues/6) and save you some time whenever the time comes.

**Comment by sindresorhus** [comment]
Done, note that new rules are also included: https://github.com/sindresorhus/eslint-config-xo/commit/83aad21cefe2e3a4c4e6b3552cf3cd85a68471ae

**Comment by justinhelmer** [comment]
FYI https://github.com/google/eslint-config-google/pull/7
