### ISSUE TITLE
Forces ecma6

### ISSUE THREAD

**Issue by sjswoboda** [sindresorhus/eslint-config-xo#16]
The new config now sets the default for ecma6. For projects that still want to use ecma5, this means that 'const' and other restricted keywords no longer throw parsing errors.

Is setting parserOptions.ecmaVersion to 6 required?

**Comment by sindresorhus** [comment]
It has almost always done that. I like it this way as it will parse anything without having to set an option. You can easily just override if you don't agree, though. That's the beauty of shareable configs :)

**Comment by sjswoboda** [comment]
It does not override, though. It will take the the plugin version...the problem is setting the parserOptions explicitly. If that's not set, all works fine. (This was added recently, https://github.com/sindresorhus/eslint-config-xo/commit/83aad21cefe2e3a4c4e6b3552cf3cd85a68471ae)

**Comment by sindresorhus** [comment]
Yes, but it already had the `es6` environment variable set, which triggered ES6 parsing implicitly. https://github.com/sindresorhus/eslint-config-xo/commit/83aad21cefe2e3a4c4e6b3552cf3cd85a68471ae#diff-168726dbe96b3ce427e7fedce31bb0bcL11 So nothing new here.

**Comment by sjswoboda** [comment]
The es6 environment variable gets overriden, however, parserOptions do not get overriden. So this is *new* and a breaking change for us.

**Comment by sindresorhus** [comment]
If you're saying you can not do the following, it sounds like a bug in ESLint and should be reported there:

```js
{
	extends: 'xo',
	parserOptions: {
		ecmaVersion: 5
	}
}
```

**Comment by sjswoboda** [comment]
Plugins override (I asked the es team); I will put in a feature request.

**Comment by sindresorhus** [comment]
@sjswoboda I know, but this is not a plugin. It's a shareable config.

**Comment by sjswoboda** [comment]
Sorry, I meant the shareable config is overriding the parser options. (no plugin here) I was under the impression that this is an eslint config -- in which case anyone using this config (esling-config-google, etc.) are all now getting "upgraded" to ecma6 because eslint does not support (currently) overriding parserOptions.

**Comment by sindresorhus** [comment]
> eslint does not support (currently) overriding parserOptions.

And if so, is a ESLint problem, and should be opened there.
