### ISSUE TITLE
Add `max-depth` rule?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-config-xo#19]
http://eslint.org/docs/rules/max-depth

I initially left it out, but might be nice to enforce less nesting.

Should we enable this or is it too opinionated? What would be a good default value?

**Comment by SamVerschueren** [comment]
Most of the times I've seen it, it was like 4 or 5. Might be nice, but I like the hear opinions from others as well.

**Comment by jamestalmage** [comment]
IMO. Use 5, and just a warning.

**Comment by sindresorhus** [comment]
@jamestalmage Do you really want to have 5 levels of nesting?

Agree with having it as a warning.

**Comment by jamestalmage** [comment]
Not in most cases. Just want to be sure whatever we pick doesn't get in people's way.

**Comment by sindresorhus** [comment]
I went with 4. I ran it on all my projects and none were more than 4. We can change it later if it becomes a problem.
