### ISSUE TITLE
Add `complexity` rule?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-config-xo#20]
http://eslint.org/docs/rules/complexity

I initially left it out in fear of it being too annoying, but it might be a good indicator of convoluted code. I would never want it as an error, but maybe it makes sense to add it as a warning so you know when developing locally if something is too complex? What would be a sensible default number?

**Comment by jamestalmage** [comment]
:+1: for a warning.

Not sure what level it should be at. Maybe try gradually reducing it on AVA until it starts reporting stuff you disagree with?
