### ISSUE TITLE
Add `max-len` rule ?

### ISSUE THREAD

**Issue by Waxo** [sindresorhus/eslint-config-xo#22]
http://eslint.org/docs/rules/max-len

I know that this rule is controversial, but in most of case developpers have their IDE configured to have 2 files side by side with the max length set to 80.

Maybe 120 and configurable in the `package.json` with an option `max-len: 80` to be less painful for common people.

**Comment by sindresorhus** [comment]
Why? Editors today can soft-wrap, so just set the line-length you prefer in your editor.

**Comment by Waxo** [comment]
Yes but not anyone is using modern editors, by the way it's an usal convention I always met. Maybe just add the option for configuration in `package.json`.

**Comment by sindresorhus** [comment]
I'm pretty sure every code editor in existence today can soft-wrap. I'm aware it's a common convention to hard-wrap, but I don't do stuff just because it's a convention. You can already use this rule yourself in your ESLint config or the `rules` option if you use XO ;)

I'll keep this open for discussion.

**Comment by Waxo** [comment]
Ok it works by using :
```js
"xo": {
    "esnext": true,
    "rules": {
      "max-len": ["error", 80, 2] // ["error", max-len, tab-witdh] (i use 2, default is 4)
    }
```

Thanks for your help ! :+1:

**Comment by bfred-it** [comment]
Editors can soft wrap, but is a line like this considered "linted"?

```jsx
const element = <div className="AvatarStack AvatarStack--three-plus AvatarStack--right clearfix d-inline-block" style={{marginTop: 1}}><div className="AvatarStack-body tooltipped tooltipped-sw tooltipped-align-right-1" aria-label={usernames}>{avatars}</div>/div>;
```
