### ISSUE TITLE
Package version is wrong?

### ISSUE THREAD

**Issue by saviomd** [sindresorhus/eslint-config-xo#31]
https://www.npmjs.com/package/eslint-config-xo is 0.15.4
https://github.com/sindresorhus/eslint-config-xo/blob/master/package.json is 0.15.2

**Comment by rgant** [comment]
Yeah, I think @sindresorhus hasn't pushed his updates to the github repository.

**Comment by sindresorhus** [comment]
I did a patch release to remove an annoying rule and forgot to push the release branch. New version is out now, so doesn't matter.
