### ISSUE TITLE
Add no-process-exit?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/eslint-config-xo#32]
> [`process.exit()`] doesn’t give the application any chance to respond to the error. It’s usually better to throw an error and allow the application to handle it appropriately

This sounds good, especially because most of the time `throw new Error()` behaves the same. 
More info: http://eslint.org/docs/rules/no-process-exit

**Comment by sindresorhus** [comment]
It's intentionally not included here, since we have [`xo/no-process-exit`](https://github.com/sindresorhus/eslint-plugin-xo/blob/master/docs/rules/no-process-exit.md) included directly in XO. See: https://github.com/eslint/eslint/issues/2666

**Comment by bfred-it** [comment]
Makes sense! I saw that ESLint was my throwing an error but xo wasn't. That's a good exception
