### ISSUE TITLE
Configuration for rule "valid-typeof" is invalid

### ISSUE THREAD

**Issue by yanivefraim** [sindresorhus/eslint-config-xo#33]
I upgraded to 0.16.0 and started to get the following errorL

> xo:
> Configuration for rule "valid-typeof" is invalid:
> Value "[object Object]" has more items than allowed.

Not sure if it is related to 0.16.0 or to new eslint (3.6.1) released two days ago...

**Comment by sindresorhus** [comment]
You need to upgrade ESLint to latest.

**Comment by yanivefraim** [comment]
Thanks!
