### ISSUE TITLE
No unused vars not working

### ISSUE THREAD

**Issue by maxime1992** [sindresorhus/eslint-config-xo#4]
First of all thanks for this nice configuration i really love it :) !

I need to customize few rules and it works great except one : no-unused-vars.
In your configuration you set it to : `'no-unused-vars': 2`.

In my tests i used should like this :
```
import shouldHttp from 'should-http';

describe('...', () => {
   it('...', done => {
      request.get('...', (err, res, body) => {
         res.should.have.status(200);
         done();
      });
   });
});
...
```

eslint think that i do not use shouldHttp.

I customized xo rules in package.json (according to [http://eslint.org/docs/rules/no-unused-vars.html](http://eslint.org/docs/rules/no-unused-vars.html)) with this rule : `"no-unused-vars": [2, {"args": "after-used", "argsIgnorePattern": "shouldHttp"}]` and i also tried  `"no-unused-vars": [2, {"args": "all", "argsIgnorePattern": "shouldHttp"}]` but nothing worked i had to make this :

```
import shouldHttp from 'should-http'; // eslint-disable-line
```

Maybe it's not a problem with xo but eslint ? (or me ...)

**Comment by sindresorhus** [comment]
Are you using the main rule or the `esnext` one? Are you using `babel-eslint`?

**Comment by maxime1992** [comment]
I do have `"esnext": true` in my package.json

**Comment by sindresorhus** [comment]
Then it might be a [babel-eslint](https://github.com/babel/babel-eslint) issue. It already has a bug with `no-unused-vars: [2, {vars: local}]`.

**Comment by maxime1992** [comment]
All right i'll search there then :) Thanks for pointing it out
