### ISSUE TITLE
Add rule global-require

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/eslint-config-xo#6]
http://eslint.org/docs/rules/global-require.html
What do you think about this rule ?

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/eslint-config-xo/commit/50629a57802f823e97e0f4ac90c189697db84948

> It's a good idea, but the reality is that it's beneficial to have some require statements inline to improve require speed. This will be moot anyways when we start using the ES2015 module system.

I had it enabled for a good while, but it were just too annoying.
